train_routes = [
    {
        "transportType": "train",
        "identifier": "T001",
        "duration": "48m",
        "departureTime": "08:00",
        "departureLocation": "HKG",
        "arrivalTime": "08:48",
        "arrivalLocation": "GZH",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 215.0
    },
    {
        "transportType": "train",
        "identifier": "T001A",
        "duration": "48m",
        "departureTime": "10:30",
        "departureLocation": "HKG",
        "arrivalTime": "11:18",
        "arrivalLocation": "GZH",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 235.0
    },
    {
        "transportType": "train",
        "identifier": "T001B",
        "duration": "48m",
        "departureTime": "14:00",
        "departureLocation": "HKG",
        "arrivalTime": "14:48",
        "arrivalLocation": "GZH",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 215.0
    },
    {
        "transportType": "train",
        "identifier": "T001C",
        "duration": "48m",
        "departureTime": "07:00",
        "departureLocation": "HKG",
        "arrivalTime": "07:48",
        "arrivalLocation": "GZH",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 205.0 
    },
    {
        "transportType": "train",
        "identifier": "T001D",
        "duration": "48m",
        "departureTime": "12:15",
        "departureLocation": "HKG",
        "arrivalTime": "13:03",
        "arrivalLocation": "GZH",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 225.0 
    },
    {
        "transportType": "train",
        "identifier": "T001E",
        "duration": "48m",
        "departureTime": "15:30",
        "departureLocation": "HKG",
        "arrivalTime": "16:18",
        "arrivalLocation": "GZH",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 235.0 
    },
    {
        "transportType": "train",
        "identifier": "T001F",
        "duration": "48m",
        "departureTime": "16:45",
        "departureLocation": "HKG",
        "arrivalTime": "17:33",
        "arrivalLocation": "GZH",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 235.0
    },
    {
        "transportType": "train",
        "identifier": "T001G",
        "duration": "48m",
        "departureTime": "18:00",
        "departureLocation": "HKG",
        "arrivalTime": "18:48",
        "arrivalLocation": "GZH",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 225.0  
    },
    {
        "transportType": "train",
        "identifier": "T001H",
        "duration": "48m",
        "departureTime": "19:30",
        "departureLocation": "HKG",
        "arrivalTime": "20:18",
        "arrivalLocation": "GZH",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 215.0  
    },
    {
        "transportType": "train",
        "identifier": "T001I",
        "duration": "48m",
        "departureTime": "21:00",
        "departureLocation": "HKG",
        "arrivalTime": "21:48",
        "arrivalLocation": "GZH",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 205.0  
    },
    {
        "transportType": "train",
        "identifier": "T002",
        "duration": "15m",
        "departureTime": "09:00",
        "departureLocation": "HKG",
        "arrivalTime": "09:15",
        "arrivalLocation": "SZX",
        "carbonEmissions": 10,
        "class": "Economy",
        "currency": "HKD",
        "price": 80.0
    },
    {
        "transportType": "train",
        "identifier": "T002A",
        "duration": "15m",
        "departureTime": "11:30",
        "departureLocation": "HKG",
        "arrivalTime": "11:45",
        "arrivalLocation": "SZX",
        "carbonEmissions": 10,
        "class": "Economy",
        "currency": "HKD",
        "price": 90.0
    },
    {
        "transportType": "train",
        "identifier": "T002B",
        "duration": "15m",
        "departureTime": "15:00",
        "departureLocation": "HKG",
        "arrivalTime": "15:15",
        "arrivalLocation": "SZX",
        "carbonEmissions": 10,
        "class": "Economy",
        "currency": "HKD",
        "price": 80.0
    },
    {
        "transportType": "train",
        "identifier": "T002C",
        "duration": "15m",
        "departureTime": "07:00",
        "departureLocation": "HKG",
        "arrivalTime": "07:15",
        "arrivalLocation": "SZX",
        "carbonEmissions": 10,
        "class": "Economy",
        "currency": "HKD",
        "price": 75.0  
    },
    {
        "transportType": "train",
        "identifier": "T002D",
        "duration": "15m",
        "departureTime": "08:15",
        "departureLocation": "HKG",
        "arrivalTime": "08:30",
        "arrivalLocation": "SZX",
        "carbonEmissions": 10,
        "class": "Economy",
        "currency": "HKD",
        "price": 85.0  
    },
    {
        "transportType": "train",
        "identifier": "T002E",
        "duration": "15m",
        "departureTime": "13:00",
        "departureLocation": "HKG",
        "arrivalTime": "13:15",
        "arrivalLocation": "SZX",
        "carbonEmissions": 10,
        "class": "Economy",
        "currency": "HKD",
        "price": 80.0
    },
    {
        "transportType": "train",
        "identifier": "T002F",
        "duration": "15m",
        "departureTime": "16:30",
        "departureLocation": "HKG",
        "arrivalTime": "16:45",
        "arrivalLocation": "SZX",
        "carbonEmissions": 10,
        "class": "Economy",
        "currency": "HKD",
        "price": 90.0  
    },
    {
        "transportType": "train",
        "identifier": "T002G",
        "duration": "15m",
        "departureTime": "17:45",
        "departureLocation": "HKG",
        "arrivalTime": "18:00",
        "arrivalLocation": "SZX",
        "carbonEmissions": 10,
        "class": "Economy",
        "currency": "HKD",
        "price": 90.0 
    },
    {
        "transportType": "train",
        "identifier": "T002H",
        "duration": "15m",
        "departureTime": "19:00",
        "departureLocation": "HKG",
        "arrivalTime": "19:15",
        "arrivalLocation": "SZX",
        "carbonEmissions": 10,
        "class": "Economy",
        "currency": "HKD",
        "price": 85.0
    },
    {
        "transportType": "train",
        "identifier": "T002I",
        "duration": "15m",
        "departureTime": "20:30",
        "departureLocation": "HKG",
        "arrivalTime": "20:45",
        "arrivalLocation": "SZX",
        "carbonEmissions": 10,
        "class": "Economy",
        "currency": "HKD",
        "price": 80.0
    },
    {
        "transportType": "train",
        "identifier": "T002J",
        "duration": "15m",
        "departureTime": "21:45",
        "departureLocation": "HKG",
        "arrivalTime": "22:00",
        "arrivalLocation": "SZX",
        "carbonEmissions": 10,
        "class": "Economy",
        "currency": "HKD",
        "price": 75.0 
    },
    {
        "transportType": "train",
        "identifier": "T003",
        "duration": "30m",
        "departureTime": "08:30",
        "departureLocation": "HKG",
        "arrivalTime": "09:00",
        "arrivalLocation": "DGG",
        "carbonEmissions": 15,
        "class": "Economy",
        "currency": "HKD",
        "price": 120.0
    },
    {
        "transportType": "train",
        "identifier": "T003A",
        "duration": "30m",
        "departureTime": "12:00",
        "departureLocation": "HKG",
        "arrivalTime": "12:30",
        "arrivalLocation": "DGG",
        "carbonEmissions": 15,
        "class": "Economy",
        "currency": "HKD",
        "price": 130.0
    },
    {
        "transportType": "train",
        "identifier": "T003B",
        "duration": "30m",
        "departureTime": "16:30",
        "departureLocation": "HKG",
        "arrivalTime": "17:00",
        "arrivalLocation": "DGG",
        "carbonEmissions": 15,
        "class": "Economy",
        "currency": "HKD",
        "price": 120.0
    },
    {
        "transportType": "train",
        "identifier": "T003C",
        "duration": "30m",
        "departureTime": "07:00",
        "departureLocation": "HKG",
        "arrivalTime": "07:30",
        "arrivalLocation": "DGG",
        "carbonEmissions": 15,
        "class": "Economy",
        "currency": "HKD",
        "price": 110.0 
    },
    {
        "transportType": "train",
        "identifier": "T003D",
        "duration": "30m",
        "departureTime": "10:15",
        "departureLocation": "HKG",
        "arrivalTime": "10:45",
        "arrivalLocation": "DGG",
        "carbonEmissions": 15,
        "class": "Economy",
        "currency": "HKD",
        "price": 120.0
    },
    {
        "transportType": "train",
        "identifier": "T003E",
        "duration": "30m",
        "departureTime": "13:45",
        "departureLocation": "HKG",
        "arrivalTime": "14:15",
        "arrivalLocation": "DGG",
        "carbonEmissions": 15,
        "class": "Economy",
        "currency": "HKD",
        "price": 125.0
    },
    {
        "transportType": "train",
        "identifier": "T003F",
        "duration": "30m",
        "departureTime": "15:00",
        "departureLocation": "HKG",
        "arrivalTime": "15:30",
        "arrivalLocation": "DGG",
        "carbonEmissions": 15,
        "class": "Economy",
        "currency": "HKD",
        "price": 130.0  
    },
    {
        "transportType": "train",
        "identifier": "T003G",
        "duration": "30m",
        "departureTime": "17:45",
        "departureLocation": "HKG",
        "arrivalTime": "18:15",
        "arrivalLocation": "DGG",
        "carbonEmissions": 15,
        "class": "Economy",
        "currency": "HKD",
        "price": 130.0 
    },
    {
        "transportType": "train",
        "identifier": "T003H",
        "duration": "30m",
        "departureTime": "19:00",
        "departureLocation": "HKG",
        "arrivalTime": "19:30",
        "arrivalLocation": "DGG",
        "carbonEmissions": 15,
        "class": "Economy",
        "currency": "HKD",
        "price": 120.0
    },
    {
        "transportType": "train",
        "identifier": "T003I",
        "duration": "30m",
        "departureTime": "20:30",
        "departureLocation": "HKG",
        "arrivalTime": "21:00",
        "arrivalLocation": "DGG",
        "carbonEmissions": 15,
        "class": "Economy",
        "currency": "HKD",
        "price": 115.0 
    },
    {
        "transportType": "train",
        "identifier": "T003J",
        "duration": "30m",
        "departureTime": "21:45",
        "departureLocation": "HKG",
        "arrivalTime": "22:15",
        "arrivalLocation": "DGG",
        "carbonEmissions": 15,
        "class": "Economy",
        "currency": "HKD",
        "price": 110.0  
    },
    {
        "transportType": "train",
        "identifier": "T004",
        "duration": "35m",
        "departureTime": "09:15",
        "departureLocation": "SZX",
        "arrivalTime": "09:50",
        "arrivalLocation": "GZH",
        "carbonEmissions": 18,
        "class": "Economy",
        "currency": "CNY",
        "price": 150.0
    },
    {
        "transportType": "train",
        "identifier": "T004A",
        "duration": "35m",
        "departureTime": "13:45",
        "departureLocation": "SZX",
        "arrivalTime": "14:20",
        "arrivalLocation": "GZH",
        "carbonEmissions": 18,
        "class": "Economy",
        "currency": "CNY",
        "price": 160.0
    },
    {
        "transportType": "train",
        "identifier": "T004B",
        "duration": "35m",
        "departureTime": "17:30",
        "departureLocation": "SZX",
        "arrivalTime": "18:05",
        "arrivalLocation": "GZH",
        "carbonEmissions": 18,
        "class": "Economy",
        "currency": "CNY",
        "price": 150.0
    },
    {
        "transportType": "train",
        "identifier": "T004C",
        "duration": "35m",
        "departureTime": "07:00",
        "departureLocation": "SZX",
        "arrivalTime": "07:35",
        "arrivalLocation": "GZH",
        "carbonEmissions": 18,
        "class": "Economy",
        "currency": "CNY",
        "price": 140.0  
    },
    {
        "transportType": "train",
        "identifier": "T004D",
        "duration": "35m",
        "departureTime": "08:15",
        "departureLocation": "SZX",
        "arrivalTime": "08:50",
        "arrivalLocation": "GZH",
        "carbonEmissions": 18,
        "class": "Economy",
        "currency": "CNY",
        "price": 155.0  
    },
    {
        "transportType": "train",
        "identifier": "T004E",
        "duration": "35m",
        "departureTime": "11:00",
        "departureLocation": "SZX",
        "arrivalTime": "11:35",
        "arrivalLocation": "GZH",
        "carbonEmissions": 18,
        "class": "Economy",
        "currency": "CNY",
        "price": 150.0
    },
    {
        "transportType": "train",
        "identifier": "T004F",
        "duration": "35m",
        "departureTime": "15:45",
        "departureLocation": "SZX",
        "arrivalTime": "16:20",
        "arrivalLocation": "GZH",
        "carbonEmissions": 18,
        "class": "Economy",
        "currency": "CNY",
        "price": 160.0  
    },
    {
        "transportType": "train",
        "identifier": "T004G",
        "duration": "35m",
        "departureTime": "16:45",
        "departureLocation": "SZX",
        "arrivalTime": "17:20",
        "arrivalLocation": "GZH",
        "carbonEmissions": 18,
        "class": "Economy",
        "currency": "CNY",
        "price": 165.0  
    },
    {
        "transportType": "train",
        "identifier": "T004H",
        "duration": "35m",
        "departureTime": "19:00",
        "departureLocation": "SZX",
        "arrivalTime": "19:35",
        "arrivalLocation": "GZH",
        "carbonEmissions": 18,
        "class": "Economy",
        "currency": "CNY",
        "price": 155.0
    },
    {
        "transportType": "train",
        "identifier": "T004I",
        "duration": "35m",
        "departureTime": "20:30",
        "departureLocation": "SZX",
        "arrivalTime": "21:05",
        "arrivalLocation": "GZH",
        "carbonEmissions": 18,
        "class": "Economy",
        "currency": "CNY",
        "price": 145.0 
    },
    {
        "transportType": "train",
        "identifier": "T004J",
        "duration": "35m",
        "departureTime": "21:45",
        "departureLocation": "SZX",
        "arrivalTime": "22:20",
        "arrivalLocation": "GZH",
        "carbonEmissions": 18,
        "class": "Economy",
        "currency": "CNY",
        "price": 140.0  
    },
    {
        "transportType": "train",
        "identifier": "T005",
        "duration": "20m",
        "departureTime": "08:45",
        "departureLocation": "GZH",
        "arrivalTime": "09:05",
        "arrivalLocation": "FSN",
        "carbonEmissions": 8,
        "class": "Economy",
        "currency": "CNY",
        "price": 45.0
    },
    {
        "transportType": "train",
        "identifier": "T005A",
        "duration": "20m",
        "departureTime": "12:15",
        "departureLocation": "GZH",
        "arrivalTime": "12:35",
        "arrivalLocation": "FSN",
        "carbonEmissions": 8,
        "class": "Economy",
        "currency": "CNY",
        "price": 50.0
    },
    {
        "transportType": "train",
        "identifier": "T005B",
        "duration": "20m",
        "departureTime": "16:45",
        "departureLocation": "GZH",
        "arrivalTime": "17:05",
        "arrivalLocation": "FSN",
        "carbonEmissions": 8,
        "class": "Economy",
        "currency": "CNY",
        "price": 45.0
    }
]

cathay_flights = [
    {
        "transportType": "plane",
        "identifier": "CX 796",
        "duration": "5h",
        "departureTime": "07:15",
        "departureLocation": "CGK",
        "arrivalTime": "12:15",
        "arrivalLocation": "HKG",
        "carbonEmissions": 180,
        "class": "Economy",
        "currency": "IDR",
        "price": 3900000.0
    },
    {
        "transportType": "plane",
        "identifier": "CX 798",
        "duration": "5h",
        "departureTime": "12:35",
        "departureLocation": "CGK",
        "arrivalTime": "17:35",
        "arrivalLocation": "HKG",
        "carbonEmissions": 180,
        "class": "Economy",
        "currency": "IDR",
        "price": 4200000.0
    },
    {
        "transportType": "plane",
        "identifier": "CX 718",
        "duration": "5h",
        "departureTime": "19:10",
        "departureLocation": "CGK",
        "arrivalTime": "00:10",
        "arrivalLocation": "HKG",
        "carbonEmissions": 180,
        "class": "Economy",
        "currency": "IDR",
        "price": 3400000.0
    },
    {
        "transportType": "plane",
        "identifier": "CX 750",
        "duration": "4h",
        "departureTime": "09:45",
        "departureLocation": "SIN",
        "arrivalTime": "13:50",
        "arrivalLocation": "HKG",
        "carbonEmissions": 165,
        "class": "Economy",
        "currency": "SGD",
        "price": 850.0
    },
    {
        "transportType": "plane",
        "identifier": "CX 734",
        "duration": "4h",
        "departureTime": "14:15",
        "departureLocation": "SIN",
        "arrivalTime": "18:20",
        "arrivalLocation": "HKG",
        "carbonEmissions": 165,
        "class": "Economy",
        "currency": "SGD",
        "price": 950.0
    },
    {
        "transportType": "plane",
        "identifier": "CX 736",
        "duration": "4h",
        "departureTime": "20:35",
        "departureLocation": "SIN",
        "arrivalTime": "00:40",
        "arrivalLocation": "HKG",
        "carbonEmissions": 165,
        "class": "Economy",
        "currency": "SGD",
        "price": 825.0
    },
]

bus_routes = [
    {
        "transportType": "bus",
        "identifier": "B001",
        "duration": "45m",
        "departureTime": "07:30",
        "departureLocation": "HKG",
        "arrivalTime": "08:15",
        "arrivalLocation": "SZX",
        "carbonEmissions": 25,
        "class": "Standard",
        "currency": "HKD",
        "price": 85.0  
    },
    {
        "transportType": "bus",
        "identifier": "B001A",
        "duration": "45m",
        "departureTime": "09:00",
        "departureLocation": "HKG",
        "arrivalTime": "09:45",
        "arrivalLocation": "SZX",
        "carbonEmissions": 25,
        "class": "Standard",
        "currency": "HKD",
        "price": 90.0
    },
    {
        "transportType": "bus",
        "identifier": "B001B",
        "duration": "45m",
        "departureTime": "11:30",
        "departureLocation": "HKG",
        "arrivalTime": "12:15",
        "arrivalLocation": "SZX",
        "carbonEmissions": 25,
        "class": "Standard",
        "currency": "HKD",
        "price": 90.0
    },
    {
        "transportType": "bus",
        "identifier": "B001C",
        "duration": "45m",
        "departureTime": "06:30",
        "departureLocation": "HKG",
        "arrivalTime": "07:15",
        "arrivalLocation": "SZX",
        "carbonEmissions": 25,
        "class": "Standard",
        "currency": "HKD",
        "price": 80.0  
    },
    {
        "transportType": "bus",
        "identifier": "B001D",
        "duration": "45m",
        "departureTime": "08:15",
        "departureLocation": "HKG",
        "arrivalTime": "09:00",
        "arrivalLocation": "SZX",
        "carbonEmissions": 25,
        "class": "Standard",
        "currency": "HKD",
        "price": 90.0 
    },
    {
        "transportType": "bus",
        "identifier": "B001E",
        "duration": "45m",
        "departureTime": "10:15",
        "departureLocation": "HKG",
        "arrivalTime": "11:00",
        "arrivalLocation": "SZX",
        "carbonEmissions": 25,
        "class": "Standard",
        "currency": "HKD",
        "price": 85.0
    },
    {
        "transportType": "bus",
        "identifier": "B001F",
        "duration": "45m",
        "departureTime": "13:00",
        "departureLocation": "HKG",
        "arrivalTime": "13:45",
        "arrivalLocation": "SZX",
        "carbonEmissions": 25,
        "class": "Standard",
        "currency": "HKD",
        "price": 85.0
    },
    {
        "transportType": "bus",
        "identifier": "B001G",
        "duration": "45m",
        "departureTime": "14:45",
        "departureLocation": "HKG",
        "arrivalTime": "15:30",
        "arrivalLocation": "SZX",
        "carbonEmissions": 25,
        "class": "Standard",
        "currency": "HKD",
        "price": 90.0 
    },
    {
        "transportType": "bus",
        "identifier": "B001H",
        "duration": "45m",
        "departureTime": "16:30",
        "departureLocation": "HKG",
        "arrivalTime": "17:15",
        "arrivalLocation": "SZX",
        "carbonEmissions": 25,
        "class": "Standard",
        "currency": "HKD",
        "price": 95.0 
    },
    {
        "transportType": "bus",
        "identifier": "B001I",
        "duration": "45m",
        "departureTime": "18:00",
        "departureLocation": "HKG",
        "arrivalTime": "18:45",
        "arrivalLocation": "SZX",
        "carbonEmissions": 25,
        "class": "Standard",
        "currency": "HKD",
        "price": 95.0  
    },
    {
        "transportType": "bus",
        "identifier": "B001J",
        "duration": "45m",
        "departureTime": "19:30",
        "departureLocation": "HKG",
        "arrivalTime": "20:15",
        "arrivalLocation": "SZX",
        "carbonEmissions": 25,
        "class": "Standard",
        "currency": "HKD",
        "price": 85.0
    },
    {
        "transportType": "bus",
        "identifier": "B001K",
        "duration": "45m",
        "departureTime": "21:00",
        "departureLocation": "HKG",
        "arrivalTime": "21:45",
        "arrivalLocation": "SZX",
        "carbonEmissions": 25,
        "class": "Standard",
        "currency": "HKD",
        "price": 80.0  
    },
    {
        "transportType": "bus",
        "identifier": "B001L",
        "duration": "45m",
        "departureTime": "22:15",
        "departureLocation": "HKG",
        "arrivalTime": "23:00",
        "arrivalLocation": "SZX",
        "carbonEmissions": 25,
        "class": "Standard",
        "currency": "HKD",
        "price": 80.0  
    },
    {
        "transportType": "bus",
        "identifier": "B002",
        "duration": "3h",
        "departureTime": "08:00",
        "departureLocation": "HKG",
        "arrivalTime": "11:00",
        "arrivalLocation": "GZH",
        "carbonEmissions": 45,
        "class": "Standard",
        "currency": "HKD",
        "price": 240.0  
    },
    {
        "transportType": "bus",
        "identifier": "B002A",
        "duration": "3h",
        "departureTime": "10:30",
        "departureLocation": "HKG",
        "arrivalTime": "13:30",
        "arrivalLocation": "GZH",
        "carbonEmissions": 45,
        "class": "Standard",
        "currency": "HKD",
        "price": 250.0
    },
    {
        "transportType": "bus",
        "identifier": "B002B",
        "duration": "3h",
        "departureTime": "14:00",
        "departureLocation": "HKG",
        "arrivalTime": "17:00",
        "arrivalLocation": "GZH",
        "carbonEmissions": 45,
        "class": "Standard",
        "currency": "HKD",
        "price": 260.0  
    },
    {
        "transportType": "bus",
        "identifier": "B002C",
        "duration": "3h",
        "departureTime": "06:30",
        "departureLocation": "HKG",
        "arrivalTime": "09:30",
        "arrivalLocation": "GZH",
        "carbonEmissions": 45,
        "class": "Standard",
        "currency": "HKD",
        "price": 230.0 
    },
    {
        "transportType": "bus",
        "identifier": "B002D",
        "duration": "3h",
        "departureTime": "09:15",
        "departureLocation": "HKG",
        "arrivalTime": "12:15",
        "arrivalLocation": "GZH",
        "carbonEmissions": 45,
        "class": "Standard",
        "currency": "HKD",
        "price": 245.0
    },
    {
        "transportType": "bus",
        "identifier": "B002E",
        "duration": "3h",
        "departureTime": "12:00",
        "departureLocation": "HKG",
        "arrivalTime": "15:00",
        "arrivalLocation": "GZH",
        "carbonEmissions": 45,
        "class": "Standard",
        "currency": "HKD",
        "price": 250.0
    },
    {
        "transportType": "bus",
        "identifier": "B002F",
        "duration": "3h",
        "departureTime": "15:30",
        "departureLocation": "HKG",
        "arrivalTime": "18:30",
        "arrivalLocation": "GZH",
        "carbonEmissions": 45,
        "class": "Standard",
        "currency": "HKD",
        "price": 260.0
    },
    {
        "transportType": "bus",
        "identifier": "B002G",
        "duration": "3h",
        "departureTime": "16:45",
        "departureLocation": "HKG",
        "arrivalTime": "19:45",
        "arrivalLocation": "GZH",
        "carbonEmissions": 45,
        "class": "Standard",
        "currency": "HKD",
        "price": 260.0  
    },
    {
        "transportType": "bus",
        "identifier": "B002H",
        "duration": "3h",
        "departureTime": "18:00",
        "departureLocation": "HKG",
        "arrivalTime": "21:00",
        "arrivalLocation": "GZH",
        "carbonEmissions": 45,
        "class": "Standard",
        "currency": "HKD",
        "price": 245.0
    },
    {
        "transportType": "bus",
        "identifier": "B002I",
        "duration": "3h",
        "departureTime": "19:30",
        "departureLocation": "HKG",
        "arrivalTime": "22:30",
        "arrivalLocation": "GZH",
        "carbonEmissions": 45,
        "class": "Standard",
        "currency": "HKD",
        "price": 240.0 
    },
    {
        "transportType": "bus",
        "identifier": "B002J",
        "duration": "3h",
        "departureTime": "21:00",
        "departureLocation": "HKG",
        "arrivalTime": "00:00",
        "arrivalLocation": "GZH",
        "carbonEmissions": 45,
        "class": "Standard",
        "currency": "HKD",
        "price": 235.0  
    },
    {
        "transportType": "bus",
        "identifier": "B002K",
        "duration": "3h",
        "departureTime": "22:30",
        "departureLocation": "HKG",
        "arrivalTime": "01:30",
        "arrivalLocation": "GZH",
        "carbonEmissions": 45,
        "class": "Standard",
        "currency": "HKD",
        "price": 230.0  
    },
    {
        "transportType": "bus",
        "identifier": "B003",
        "duration": "2h",
        "departureTime": "07:45",
        "departureLocation": "HKG",
        "arrivalTime": "09:45",
        "arrivalLocation": "DGG",
        "carbonEmissions": 35,
        "class": "Standard",
        "currency": "HKD",
        "price": 155.0  
    },
    {
        "transportType": "bus",
        "identifier": "B003A",
        "duration": "2h",
        "departureTime": "11:15",
        "departureLocation": "HKG",
        "arrivalTime": "13:15",
        "arrivalLocation": "DGG",
        "carbonEmissions": 35,
        "class": "Standard",
        "currency": "HKD",
        "price": 160.0
    },
    {
        "transportType": "bus",
        "identifier": "B003B",
        "duration": "2h",
        "departureTime": "15:30",
        "departureLocation": "HKG",
        "arrivalTime": "17:30",
        "arrivalLocation": "DGG",
        "carbonEmissions": 35,
        "class": "Standard",
        "currency": "HKD",
        "price": 165.0  
    },
    {
        "transportType": "bus",
        "identifier": "B004",
        "duration": "3h 30m",
        "departureTime": "08:30",
        "departureLocation": "HKG",
        "arrivalTime": "12:00",
        "arrivalLocation": "FSH",
        "carbonEmissions": 50,
        "class": "Standard",
        "currency": "HKD",
        "price": 270.0 
    },
    {
        "transportType": "bus",
        "identifier": "B004A",
        "duration": "3h 30m",
        "departureTime": "12:00",
        "departureLocation": "HKG",
        "arrivalTime": "15:30",
        "arrivalLocation": "FSH",
        "carbonEmissions": 50,
        "class": "Standard",
        "currency": "HKD",
        "price": 280.0
    },
    {
        "transportType": "bus",
        "identifier": "B004B",
        "duration": "3h 30m",
        "departureTime": "15:30",
        "departureLocation": "HKG",
        "arrivalTime": "19:00",
        "arrivalLocation": "FSH",
        "carbonEmissions": 50,
        "class": "Standard",
        "currency": "HKD",
        "price": 290.0  
    }
]

ferry_routes = [
    {
        "transportType": "ferry",
        "identifier": "F001",
        "duration": "1h",
        "departureTime": "07:00",
        "departureLocation": "HKG",
        "arrivalTime": "08:00",
        "arrivalLocation": "MFM",
        "carbonEmissions": 30,
        "class": "Economy",
        "currency": "HKD",
        "price": 171.0
    },
    {
        "transportType": "ferry",
        "identifier": "F001A",
        "duration": "1h",
        "departureTime": "09:30",
        "departureLocation": "HKG",
        "arrivalTime": "10:30",
        "arrivalLocation": "MFM",
        "carbonEmissions": 30,
        "class": "Economy",
        "currency": "HKD",
        "price": 180.0 
    },
    {
        "transportType": "ferry",
        "identifier": "F001B",
        "duration": "1h",
        "departureTime": "12:00",
        "departureLocation": "HKG",
        "arrivalTime": "13:00",
        "arrivalLocation": "MFM",
        "carbonEmissions": 30,
        "class": "Economy",
        "currency": "HKD",
        "price": 175.0
    },
{
        "transportType": "ferry",
        "identifier": "F001C",
        "duration": "1h",
        "departureTime": "06:00",
        "departureLocation": "HKG",
        "arrivalTime": "07:00",
        "arrivalLocation": "MFM",
        "carbonEmissions": 30,
        "class": "Economy",
        "currency": "HKD",
        "price": 165.0  
    },
    {
        "transportType": "ferry",
        "identifier": "F001D",
        "duration": "1h",
        "departureTime": "08:15",
        "departureLocation": "HKG",
        "arrivalTime": "09:15",
        "arrivalLocation": "MFM",
        "carbonEmissions": 30,
        "class": "Economy",
        "currency": "HKD",
        "price": 175.0
    },
    {
        "transportType": "ferry",
        "identifier": "F001E",
        "duration": "1h",
        "departureTime": "10:45",
        "departureLocation": "HKG",
        "arrivalTime": "11:45",
        "arrivalLocation": "MFM",
        "carbonEmissions": 30,
        "class": "Economy",
        "currency": "HKD",
        "price": 180.0  
    },
    {
        "transportType": "ferry",
        "identifier": "F001F",
        "duration": "1h",
        "departureTime": "13:30",
        "departureLocation": "HKG",
        "arrivalTime": "14:30",
        "arrivalLocation": "MFM",
        "carbonEmissions": 30,
        "class": "Economy",
        "currency": "HKD",
        "price": 175.0
    },
    {
        "transportType": "ferry",
        "identifier": "F001G",
        "duration": "1h",
        "departureTime": "15:00",
        "departureLocation": "HKG",
        "arrivalTime": "16:00",
        "arrivalLocation": "MFM",
        "carbonEmissions": 30,
        "class": "Economy",
        "currency": "HKD",
        "price": 180.0  
    },
    {
        "transportType": "ferry",
        "identifier": "F001H",
        "duration": "1h",
        "departureTime": "16:30",
        "departureLocation": "HKG",
        "arrivalTime": "17:30",
        "arrivalLocation": "MFM",
        "carbonEmissions": 30,
        "class": "Economy",
        "currency": "HKD",
        "price": 185.0  
    },
    {
        "transportType": "ferry",
        "identifier": "F001I",
        "duration": "1h",
        "departureTime": "18:00",
        "departureLocation": "HKG",
        "arrivalTime": "19:00",
        "arrivalLocation": "MFM",
        "carbonEmissions": 30,
        "class": "Economy",
        "currency": "HKD",
        "price": 180.0
    },
    {
        "transportType": "ferry",
        "identifier": "F001J",
        "duration": "1h",
        "departureTime": "19:30",
        "departureLocation": "HKG",
        "arrivalTime": "20:30",
        "arrivalLocation": "MFM",
        "carbonEmissions": 30,
        "class": "Economy",
        "currency": "HKD",
        "price": 175.0
    },
    {
        "transportType": "ferry",
        "identifier": "F001K",
        "duration": "1h",
        "departureTime": "21:00",
        "departureLocation": "HKG",
        "arrivalTime": "22:00",
        "arrivalLocation": "MFM",
        "carbonEmissions": 30,
        "class": "Economy",
        "currency": "HKD",
        "price": 170.0  
    },
    {
        "transportType": "ferry",
        "identifier": "F001L",
        "duration": "1h",
        "departureTime": "22:30",
        "departureLocation": "HKG",
        "arrivalTime": "23:30",
        "arrivalLocation": "MFM",
        "carbonEmissions": 30,
        "class": "Economy",
        "currency": "HKD",
        "price": 165.0  
    },
    {
        "transportType": "ferry",
        "identifier": "F002",
        "duration": "1h 10m",
        "departureTime": "08:15",
        "departureLocation": "HKG",
        "arrivalTime": "09:25",
        "arrivalLocation": "ZUH",
        "carbonEmissions": 35,
        "class": "Economy",
        "currency": "HKD",
        "price": 165.0
    },
    {
        "transportType": "ferry",
        "identifier": "F002A",
        "duration": "1h 10m",
        "departureTime": "11:45",
        "departureLocation": "HKG",
        "arrivalTime": "12:55",
        "arrivalLocation": "ZUH",
        "carbonEmissions": 35,
        "class": "Economy",
        "currency": "HKD",
        "price": 175.0  # Peak time
    },
    {
        "transportType": "ferry",
        "identifier": "F002B",
        "duration": "1h 10m",
        "departureTime": "15:30",
        "departureLocation": "HKG",
        "arrivalTime": "16:40",
        "arrivalLocation": "ZUH",
        "carbonEmissions": 35,
        "class": "Economy",
        "currency": "HKD",
        "price": 170.0
    },  
    {
        "transportType": "ferry",
        "identifier": "F004",
        "duration": "30m",
        "departureTime": "09:00",
        "departureLocation": "HKG",
        "arrivalTime": "09:30",
        "arrivalLocation": "SZX",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 120.0
    },
    {
        "transportType": "ferry",
        "identifier": "F004A",
        "duration": "30m",
        "departureTime": "13:30",
        "departureLocation": "HKG",
        "arrivalTime": "14:00",
        "arrivalLocation": "SZX",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 130.0  
    },
    {
        "transportType": "ferry",
        "identifier": "F004B",
        "duration": "30m",
        "departureTime": "17:45",
        "departureLocation": "HKG",
        "arrivalTime": "18:15",
        "arrivalLocation": "SZX",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 125.0
    },
    {
        "transportType": "ferry",
        "identifier": "F004C",
        "duration": "30m",
        "departureTime": "07:00",
        "departureLocation": "HKG",
        "arrivalTime": "07:30",
        "arrivalLocation": "SZX",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 115.0 
    },
    {
        "transportType": "ferry",
        "identifier": "F004D",
        "duration": "30m",
        "departureTime": "08:15",
        "departureLocation": "HKG",
        "arrivalTime": "08:45",
        "arrivalLocation": "SZX",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 125.0  
    },
    {
        "transportType": "ferry",
        "identifier": "F004E",
        "duration": "30m",
        "departureTime": "10:30",
        "departureLocation": "HKG",
        "arrivalTime": "11:00",
        "arrivalLocation": "SZX",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 120.0
    },
    {
        "transportType": "ferry",
        "identifier": "F004F",
        "duration": "30m",
        "departureTime": "11:45",
        "departureLocation": "HKG",
        "arrivalTime": "12:15",
        "arrivalLocation": "SZX",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 120.0
    },
    {
        "transportType": "ferry",
        "identifier": "F004G",
        "duration": "30m",
        "departureTime": "15:15",
        "departureLocation": "HKG",
        "arrivalTime": "15:45",
        "arrivalLocation": "SZX",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 130.0  
    },
    {
        "transportType": "ferry",
        "identifier": "F004H",
        "duration": "30m",
        "departureTime": "16:30",
        "departureLocation": "HKG",
        "arrivalTime": "17:00",
        "arrivalLocation": "SZX",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 135.0 
    },
    {
        "transportType": "ferry",
        "identifier": "F004I",
        "duration": "30m",
        "departureTime": "19:00",
        "departureLocation": "HKG",
        "arrivalTime": "19:30",
        "arrivalLocation": "SZX",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 125.0
    },
    {
        "transportType": "ferry",
        "identifier": "F004J",
        "duration": "30m",
        "departureTime": "20:15",
        "departureLocation": "HKG",
        "arrivalTime": "20:45",
        "arrivalLocation": "SZX",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 120.0
    },
    {
        "transportType": "ferry",
        "identifier": "F004K",
        "duration": "30m",
        "departureTime": "21:30",
        "departureLocation": "HKG",
        "arrivalTime": "22:00",
        "arrivalLocation": "SZX",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 115.0  
    },
    {
        "transportType": "ferry",
        "identifier": "F004L",
        "duration": "30m",
        "departureTime": "22:45",
        "departureLocation": "HKG",
        "arrivalTime": "23:15",
        "arrivalLocation": "SZX",
        "carbonEmissions": 20,
        "class": "Economy",
        "currency": "HKD",
        "price": 110.0 
    },
    {
        "transportType": "ferry",
        "identifier": "F005",
        "duration": "20m",
        "departureTime": "08:30",
        "departureLocation": "ZUH",
        "arrivalTime": "08:50",
        "arrivalLocation": "MFM",
        "carbonEmissions": 15,
        "class": "Economy",
        "currency": "HKD",
        "price": 80.0
    },
    {
        "transportType": "ferry",
        "identifier": "F005A",
        "duration": "20m",
        "departureTime": "12:45",
        "departureLocation": "ZUH",
        "arrivalTime": "13:05",
        "arrivalLocation": "MFM",
        "carbonEmissions": 15,
        "class": "Economy",
        "currency": "HKD",
        "price": 85.0 
    },
    {
        "transportType": "ferry",
        "identifier": "F005B",
        "duration": "20m",
        "departureTime": "16:15",
        "departureLocation": "ZUH",
        "arrivalTime": "16:35",
        "arrivalLocation": "MFM",
        "carbonEmissions": 15,
        "class": "Economy",
        "currency": "HKD",
        "price": 82.0
    }
]